### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by alkamin** [raster-foundry/blasterjs#1]
We should include some basic guides on:
- [ ] creating new components
- [ ] creating new packages
- [ ] preferring styled-components

**Comment by designmatty** [comment]
@alkamin can you get on this soon?

**Comment by alkamin** [comment]
@designmatty for sure, already done

**Comment by alkamin** [comment]
@designmatty oops sorry not quite yet

**Comment by alkamin** [comment]
README has been improved, we can keep improving it as needed with PRs
