### ISSUE TITLE
Doc deployment bug, reset stylesheet not working

### ISSUE THREAD

**Issue by designmatty** [raster-foundry/blasterjs#110]
Seems like a MIME type issue. We should simply need to update the `<link>` tag to include `type="text/css"`

![image](https://user-images.githubusercontent.com/1928955/49098515-0e33c200-f23d-11e8-9351-aee28b08ef3c.png)
![image](https://user-images.githubusercontent.com/1928955/49098653-679bf100-f23d-11e8-97b0-1fa83618a767.png)

**Comment by alkamin** [comment]
Closed by #111
