### ISSUE TITLE
Revert the decision to use tag prop instead of as

### ISSUE THREAD

**Issue by designmatty** [raster-foundry/blasterjs#182]
Originally, `tag` was conceived to fix an issue we had been experiencing with the way we were utilizing `Box` as the basis for every component. See https://github.com/raster-foundry/blasterjs/pull/116

Now that we are pushing out a functional change to how every component is created (see #180) the `tag` prop is no longer necessary.

**Comment by lederer** [comment]
This is also a good opportunity to update the Box docs page for the new theme system. Much of its content is no longer accurate.

**Comment by designmatty** [comment]
The only component that still uses tag is `Box`. There are two retired components which should be removed from the library entirely as part of this issue: `field` and `togglefield`
