### ISSUE TITLE
Setup up deployment to Netlify for develop branch

### ISSUE THREAD

**Issue by designmatty** [raster-foundry/blasterjs#189]
along with any branches against develop

**Comment by hectcastro** [comment]
I add https://github.com/raster-foundry/blasterjs/commit/4eab97f8a2d5ecee24a137aa543284e1e9c887f3 against `develop` to trigger a build. That build is visible [here](https://develop--raster-foundry-blaster.netlify.com/), but the docz site does not seem to render (`RangeError: Maximum call stack size exceeded`).

**Comment by designmatty** [comment]
I'll look into this.

**Comment by designmatty** [comment]
This is confirmed working now with #191 . Thanks for the help.
