### ISSUE TITLE
Research tab only focus states

### ISSUE THREAD

**Issue by designmatty** [raster-foundry/blasterjs#207]
**Enhancement suggestion:**
Jeff suggested implementing a way to only show `:focus` outline/box-shadow when the user tabs to the element, rather than if the user were to click on the element. There are a lot of potential solutions but this would require some research to do this in an accessible-friendly way. This would apply to clickable elements such as `<Button>` or `<A>`

**Some potential reading:**
- https://hackernoon.com/one-line-of-code-to-remove-focus-blue-outline-and-keep-accessibility-bca3ccea9892
- https://jmperezperez.com/outline-focus-ring-a11y/
- https://stackoverflow.com/questions/31402576/enable-focus-only-on-keyboard-use-or-tab-press

**Comment by lederer** [comment]
👍 A number of Azavea project use focus-visible for this. https://github.com/WICG/focus-visible
