### ISSUE TITLE
Overlay opening a new overlay makes _two_ overlays

### ISSUE THREAD

**Issue by jisantuc** [raster-foundry/blasterjs#221]
![image](https://user-images.githubusercontent.com/5702984/63619492-68876680-c5b4-11e9-9615-b18655d82318.png)

If you open an overlay from within another overlay... the overlays end up overlaid, in the sense that the area outside the overlays ends up doubly darkened, and you can still see the other overlay box below. I'd include a screenshot but it's from a secret repo, ask me if you want to see an example

**Comment by alkamin** [comment]
I think this should be solved within the application...at least for v1.
