### ISSUE TITLE
Nested Text components don't inherit styles as expected

### ISSUE THREAD

**Issue by alkamin** [raster-foundry/blasterjs#234]
It's possible that this is just a bad assumption, but doing the following resulted in unexpected results:

```
<Text fontSize={4}>
   <Text fontWeight="bold">Hello</Text>World
</Text>
```

![image](https://user-images.githubusercontent.com/2442245/66263487-7b9b7200-e7c1-11e9-8035-3ed3098a3f8a.png)

I expected the inner `Text` component to also have a `fontSize` of `4`.

**Comment by designmatty** [comment]
I think that's a safe assumption. If I were to write the html `<p>...<span>...</span></p>` I would expect the `span` to be the same size as the `p` unless I manually changed it.

This would be a pretty straightforward fix, by setting a default prop for `fontSize = inherit`. We should ensure this doesn't have any unintended issues though.

I manually tested this fix by setting fontSize to inherit in this example and it works well, so I assume a default prop will work just as well:
![image](https://user-images.githubusercontent.com/1928955/66605427-14ddd600-eb7e-11e9-91eb-0af7c61f2c6c.png)

I also checked to see if any other props would need this treatment, but it doesn't seem to be the case.
