### ISSUE TITLE
Can't set z-index of tooltip

### ISSUE THREAD

**Issue by alkamin** [raster-foundry/blasterjs#239]
Tried:
- `<Tooltip zIndex="2">`
- 
```jsx
  const StyledTooltip = styled(Tooltip)`z-index: 2`;
```

While the latter does get a style applied on an element (TooltipContent), it has no effect likely due to positioning of parent elements.

**Comment by designmatty** [comment]
I think we should set a really high, hard definition of the z-index. Tooltips should always have the highest z-ordering.

**Comment by designmatty** [comment]
And it doesn't seem like something that should be overridden.
